# Generated by Django 5.2.3 on 2025-11-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemahorista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='salario_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salario',
            name='salario_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salario',
            name='quantidade_horas_trabalhadas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Trabalhadas'),
        ),
    ]
